all:
	@echo [Linux] Building updateable ELF...
	@make -s updateable_elf

dev:
	@echo [Linux] Building developer ELF...
	@make -s elf

dev_verbose:
	@echo [Linux] Building developer ELF with verbose output...
	@make elf