/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2014 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "../pinc.h"

#define CMDNAME "pchat"


//-------------------------------------------------------------------------
// Function declarations

void __cdecl SendChatToAllAdmins(const char *a1, const char *line);
void SV_PChatCmd_f();

//-------------------------------------------------------------------------
// Data declarations


//----- (00000720) --------------------------------------------------------
void __cdecl SendChatToAllAdmins(const char *a1, const char *line)
{
  int i; // ebx@1

  for ( i = 0; i < Plugin_GetSlotCount(); ++i )
  {
    if ( Plugin_CanPlayerUseCommand(i, CMDNAME) )
    {
      Plugin_ChatPrintf(i, "^3[^0AdminChat^3]^7 (%s^7): %s", a1, line);
    }
  }
}
// 1C48: using guessed type int Plugin_GetSlotCount(void);
// 1C5C: using guessed type int Plugin_ChatPrintf(_DWORD, const char *, ...);
// 1C6C: using guessed type int __cdecl Plugin_GetClientForClientNum(_DWORD);

//----- (0000077D) --------------------------------------------------------
void SV_PChatCmd_f()
{
  int clientnum; // eax@5
  const char *chattername; // eax@5
  char line[256]; // [sp+10h] [bp-108h]@3

  if ( Plugin_Cmd_Argc() > 1 )
  {
    Plugin_Cmd_Args(line, sizeof(line));
    if ( Plugin_Cmd_GetInvokerSlot() >= 0 )
    {
      clientnum = Plugin_Cmd_GetInvokerSlot();
      chattername = Plugin_GetPlayerName(clientnum);
      SendChatToAllAdmins(chattername, line);
    }
    else
    {
      SendChatToAllAdmins("Server", line);
    }
  }
  else
  {
    Plugin_Printf("Usage: $pchat <Message>\n^3This command is used to send messages to other admins.\n^3Only admins who are logged in will be able to see your messages and communicate using the admin chat system\n");
  }
}
// 1C54: using guessed type int Plugin_Cmd_Argc(void);
// 1C58: using guessed type int __cdecl Plugin_Cmd_Args(_DWORD, _DWORD);
// 1C64: using guessed type int __cdecl Plugin_Printf(_DWORD);
// 1C74: using guessed type int Plugin_Cmd_GetInvokerSlot(void);


PCL void OnInfoRequest(pluginInfo_t *info){	// Function used to obtain information about the plugin
    // Memory pointed by info is allocated by the server binary, just fill in the fields

    // =====  MANDATORY FIELDS  =====
    info->handlerVersion.major = PLUGIN_HANDLER_VERSION_MAJOR;
    info->handlerVersion.minor = PLUGIN_HANDLER_VERSION_MINOR;	// Requested handler version

    // =====  OPTIONAL  FIELDS  =====
    info->pluginVersion.major = 1;
    info->pluginVersion.minor = 0;	// Plugin version
    strncpy(info->fullName,"Private Chat Plugin by NNJ", sizeof(info->fullName)); //Full plugin name
    strncpy(info->shortDescription,"Private Chat Plugin by NNJ",sizeof(info->shortDescription)); // Short plugin description
    strncpy(info->longDescription,"This plugin is used to privately chat with admins while in-game. Plugin By NNJ.",sizeof(info->longDescription));
}

//----- (00000878) --------------------------------------------------------
int OnInit()
{
  Plugin_AddCommand(CMDNAME, SV_PChatCmd_f, 10);
  return 0;
}

// ALL OK, 10 function(s) have been successfully decompiled
