#include "bg_weapons_load_obj.hpp"

#include "xassets/weapondef.hpp"


extern "C"
{
    char bg_defaultWeaponDefs[0x880];
    char g_playerAnimTypeNames[0x100];
    char g_playerAnimTypeNamesCount[0x80];
    char surfaceTypeSoundListCount[0x1c];
    char surfaceTypeSoundLists[0xe0];


    const char* szWeapTypeNames[4] =
    {
        "bullet",
        "grenade",
        "projectile",
        "binoculars"
    };

    const char* szWeapClassNames[10] =
    {
        "rifle",
        "mg",
        "smg",
        "spread",
        "pistol",
        "grenade",
        "rocketlauncher",
        "turret",
        "non-player",
        "item"
    };

    const char* szWeapOverlayReticleNames[2] =
    {
        "none",
        "crosshair"
    };

    const char* szWeapInventoryTypeNames[4] =
    {
        "primary",
        "offhand",
        "item",
        "altmode"
    };

    const char* szWeapFireTypeNames[5] =
    {
        "Full Auto",
        "Single Shot",
        "2-Round Burst",
        "3-Round Burst",
        "4-Round Burst"
    };

    const char* penetrateTypeNames[4] =
    {
        "none",
        "small",
        "medium",
        "large"
    };

    const char* impactTypeNames[9] =
    {
        "none",
        "bullet_small",
        "bullet_large",
        "bullet_ap",
        "shotgun",
        "grenade_bounce",
        "grenade_explode",
        "rocket_explode",
        "projectile_dud"
    };

    const char* szWeapStanceNames[3] =
    {
        "stand",
        "duck",
        "prone"
    };

    const char* szProjectileExplosionNames[7] =
    {
        "grenade",
        "rocket",
        "flashbang",
        "none",
        "dud",
        "smoke",
        "heavy explosive"
    };

    const char* offhandClassNames[4] =
    {
        "None",
        "Frag Grenade",
        "Smoke Grenade",
        "Flash Grenade"
    };

    const char* activeReticleNames[3] =
    {
        "None",
        "Pip-On-A-Stick",
        "Bouncing diamond"
    };

    const char* guidedMissileNames[4] =
    {
        "None",
        "Sidewinder",
        "Hellfire",
        "Javelin"
    };

    const char* stickinessNames[4] =
    {
        "Don't stick",
        "Stick to all",
        "Stick to ground",
        "Stick to ground, maintain yaw"
    };

    const char* overlayInterfaceNames[3] =
    {
        "None",
        "Javelin",
        "Turret Scope"
    };

    const char* ammoCounterClipNames[7] =
    {
        "None",
        "Magazine",
        "ShortMagazine",
        "Shotgun",
        "Rocket",
        "Beltfed",
        "AltWeapon"
    };

    const char* weapIconRatioNames[3] =
    {
        "1:1",
        "2:1",
        "4:1"
    };

#define WEAPONDEF_OFFSET(__field__) ((int)&(((WeaponDef*)0)->__field__))
#define WEAPONDEF_FIELD(__text__, __field__) __text__, WEAPONDEF_OFFSET(__field__)

    cspField_t weaponDefFields[502] =
    {
        // To be done later. Not a point at now.
        //{ WEAPONDEF_FIELD("displayName", szDisplayName), 0 },
        //{ WEAPONDEF_FIELD("AIOverlayDescription", szOverlayName), 0 },
        //{ WEAPONDEF_FIELD("playerAnimType", playerAnimType), 0x14 },
        //{ WEAPONDEF_FIELD("gunModel",   gunXModel[0]), 9 },
        //{ WEAPONDEF_FIELD("gunModel2",  gunXModel[1]), 9 },
        //{ WEAPONDEF_FIELD("gunModel3",  gunXModel[2]), 9 },
        //{ WEAPONDEF_FIELD("gunModel4",  gunXModel[3]), 9 },
        //{ WEAPONDEF_FIELD("gunModel5",  gunXModel[4]), 9 },
        //{ WEAPONDEF_FIELD("gunModel6",  gunXModel[5]), 9 },
        //{ WEAPONDEF_FIELD("gunModel7",  gunXModel[6]), 9 },
        //{ WEAPONDEF_FIELD("gunModel8",  gunXModel[7]), 9 },
        //{ WEAPONDEF_FIELD("gunModel9",  gunXModel[8]), 9 },
        //{ WEAPONDEF_FIELD("gunModel10", gunXModel[9]), 9 },
        //{ WEAPONDEF_FIELD("gunModel11", gunXModel[10]), 9 },
        //{ WEAPONDEF_FIELD("gunModel12", gunXModel[11]), 9 },
        //{ WEAPONDEF_FIELD("gunModel13", gunXModel[12]), 9 },
        //{ WEAPONDEF_FIELD("gunModel14", gunXModel[13]), 9 },
        //{ WEAPONDEF_FIELD("gunModel15", gunXModel[14]), 9 },
        //{ WEAPONDEF_FIELD("gunModel16", gunXModel[15]), 9 },
        //{ WEAPONDEF_FIELD("handModel", handXModel), 9 },
        //{ WEAPONDEF_FIELD("hideTags", hideTags[0]), 0x21 },
        //{ WEAPONDEF_FIELD("notetrackSoundMap", notetrackSoundMapKeys[0]), 0x22 },
        //{ WEAPONDEF_FIELD("idleAnim", szXAnims[0]), 0 },
        //{ WEAPONDEF_FIELD("emptyIdleAnim", szXAnims[1]), 0 },
        //{ WEAPONDEF_FIELD("holdFireAnim", szXAnims[2]), 0 },
        //{ WEAPONDEF_FIELD("lastShotAnim", szXAnims[3]), 0 },
        //{ WEAPONDEF_FIELD("rechamberAnim", szXAnims[4]), 0 },
        //{ WEAPONDEF_FIELD("meleeAnim", szXAnims[5]), 0 },
        //{ WEAPONDEF_FIELD("meleeChargeAnim", szXAnims[6]), 0 },
        //{ WEAPONDEF_FIELD("reloadAnim", szXAnims[7]), 0 },
        //{ WEAPONDEF_FIELD("reloadStartAnim", szXAnims[8]), 0 },
        //{ WEAPONDEF_FIELD("reloadEndAnim", szXAnims[9]), 0 },
        //{ WEAPONDEF_FIELD("raiseAnim", szXAnims[10]), 0 },
        //{ WEAPONDEF_FIELD("firstRaiseAnim", szXAnims[11]), 0 },
        //{ WEAPONDEF_FIELD("dropAnim", szXAnims[12]), 0 },
        //{ WEAPONDEF_FIELD("altRaiseAnim", szXAnims[13]), 0 },
        //{ WEAPONDEF_FIELD("altDropAnim", szXAnims[14]), 0 },
        //{ WEAPONDEF_FIELD("quickRaiseAnim", szXAnims[15]), 0 },
        //{ WEAPONDEF_FIELD("quickDropAnim", szXAnims[16]), 0 },
        //{ WEAPONDEF_FIELD("emptyRaiseAnim", szXAnims[17]), 0 },
        //{ WEAPONDEF_FIELD("emptyDropAnim", szXAnims[18]), 0 },
        //{ WEAPONDEF_FIELD("sprintInAnim", szXAnims[19]), 0 },
        //{ WEAPONDEF_FIELD("sprintLoopAnim", szXAnims[20]), 0 },
        //{ WEAPONDEF_FIELD("sprintOutAnim", szXAnims[21]), 0 },
        //{ WEAPONDEF_FIELD("detonateAnim", szXAnims[22]), 0 },
        //{ WEAPONDEF_FIELD("nightVisionWearAnim", szXAnims[23]), 0 },
        //{ WEAPONDEF_FIELD("nightVisionRemoveAnim", szXAnims[24]), 0 },
        //{ WEAPONDEF_FIELD("adsFireAnim", szXAnims[25]), 0 },
        //{ WEAPONDEF_FIELD("adsLastShotAnim", szXAnims[26]), 0 },
        //{ WEAPONDEF_FIELD("adsRechamberAnim", szXAnims[27]), 0 },
        //{ WEAPONDEF_FIELD("adsUpAnim", szXAnims[28]), 0 },
        //{ WEAPONDEF_FIELD("adsDownAnim", szXAnims[29]), 0 },
        //{ WEAPONDEF_FIELD("script", szScript), 0 }, // 7f4
        //{ WEAPONDEF_FIELD("weaponType", weapType), 0xC },
        //{ WEAPONDEF_FIELD("weaponClass", weapClass), 0xD },
        //{ WEAPONDEF_FIELD("penetrateType", ), 0xF },
        //{ WEAPONDEF_FIELD("impactType", ), 0x10 },
        //{ WEAPONDEF_FIELD("inventoryType", ), 0x1A },
        //{ WEAPONDEF_FIELD("fireType", ), 0x1B },
        //{ WEAPONDEF_FIELD("offhandClass", ), 0x13 },
        //{ WEAPONDEF_FIELD("viewFlashEffect", ), 8 },
        //{ WEAPONDEF_FIELD("worldFlashEffect", ), 8 },
        //{ WEAPONDEF_FIELD("pickupSound", ), 0xB },
        //{ WEAPONDEF_FIELD("pickupSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("ammoPickupSound", ), 0xB },
        //{ WEAPONDEF_FIELD("ammoPickupSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("projectileSound", ), 0xB },
        //{ WEAPONDEF_FIELD("pullbackSound", ), 0xB },
        //{ WEAPONDEF_FIELD("pullbackSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("fireSound", ), 0xB },
        //{ WEAPONDEF_FIELD("fireSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("loopFireSound", ), 0xB },
        //{ WEAPONDEF_FIELD("loopFireSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("stopFireSound", ), 0xB },
        //{ WEAPONDEF_FIELD("stopFireSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("lastShotSound", ), 0xB },
        //{ WEAPONDEF_FIELD("lastShotSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("emptyFireSound", ), 0xB },
        //{ WEAPONDEF_FIELD("emptyFireSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("meleeSwipeSound", ), 0xB },
        //{ WEAPONDEF_FIELD("meleeSwipeSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("meleeHitSound", ), 0xB },
        //{ WEAPONDEF_FIELD("meleeMissSound", ), 0xB },
        //{ WEAPONDEF_FIELD("rechamberSound", ), 0xB },
        //{ WEAPONDEF_FIELD("rechamberSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("reloadSound", ), 0xB },
        //{ WEAPONDEF_FIELD("reloadSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("reloadEmptySound", ), 0xB },
        //{ WEAPONDEF_FIELD("reloadEmptySoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("reloadStartSound", ), 0xB },
        //{ WEAPONDEF_FIELD("reloadStartSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("reloadEndSound", ), 0xB },
        //{ WEAPONDEF_FIELD("reloadEndSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("detonateSound", ), 0xB },
        //{ WEAPONDEF_FIELD("detonateSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("nightVisionWearSound", ), 0xB },
        //{ WEAPONDEF_FIELD("nightVisionWearSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("nightVisionRemoveSound", ), 0xB },
        //{ WEAPONDEF_FIELD("nightVisionRemoveSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("raiseSound", ), 0xB },
        //{ WEAPONDEF_FIELD("raiseSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("firstRaiseSound", ), 0xB },
        //{ WEAPONDEF_FIELD("firstRaiseSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("altSwitchSound", ), 0xB },
        //{ WEAPONDEF_FIELD("altSwitchSoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("putawaySound", ), 0xB },
        //{ WEAPONDEF_FIELD("putawaySoundPlayer", ), 0xB },
        //{ WEAPONDEF_FIELD("bounceSound", ), 0x17 },
        //{ WEAPONDEF_FIELD("viewShellEjectEffect", ), 8 },
        //{ WEAPONDEF_FIELD("worldShellEjectEffect", ), 8 },
        //{ WEAPONDEF_FIELD("viewLastShotEjectEffect", ), 8 },
        //{ WEAPONDEF_FIELD("worldLastShotEjectEffect", ), 8 },
        //{ WEAPONDEF_FIELD("reticleCenter", ), 0xA },
        //{ WEAPONDEF_FIELD("reticleSide", ), 0xA },
        //{ WEAPONDEF_FIELD("reticleCenterSize", ), 4 },
        //{ WEAPONDEF_FIELD("reticleSideSize", ), 4 },
        //{ WEAPONDEF_FIELD("reticleMinOfs", ), 4 },
        //{ WEAPONDEF_FIELD("activeReticleType", ), 0x15 },
        //{ WEAPONDEF_FIELD("standMoveF", ), 6 },
        //{ WEAPONDEF_FIELD("standMoveR", ), 6 },
        //{ WEAPONDEF_FIELD("standMoveU", ), 6 },
        //{ WEAPONDEF_FIELD("standRotP", ), 6 },
        //{ WEAPONDEF_FIELD("standRotY", ), 6 },
        //{ WEAPONDEF_FIELD("standRotR", ), 6 },
        //{ WEAPONDEF_FIELD("duckedOfsF", ), 6 },
        //{ WEAPONDEF_FIELD("duckedOfsR", ), 6 },
        //{ WEAPONDEF_FIELD("duckedOfsU", ), 6 },
        //{ WEAPONDEF_FIELD("duckedMoveF", ), 6 },
        //{ WEAPONDEF_FIELD("duckedMoveR", ), 6 },
        //{ WEAPONDEF_FIELD("duckedMoveU", ), 6 },
        //{ WEAPONDEF_FIELD("duckedRotP", ), 6 },
        //{ WEAPONDEF_FIELD("duckedRotY", ), 6 },
        //{ WEAPONDEF_FIELD("duckedRotR", ), 6 },
        //{ WEAPONDEF_FIELD("proneOfsF", ), 6 },
        //{ WEAPONDEF_FIELD("proneOfsR", ), 6 },
        //{ WEAPONDEF_FIELD("proneOfsU", ), 6 },
        //{ WEAPONDEF_FIELD("proneMoveF", ), 6 },
        //{ WEAPONDEF_FIELD("proneMoveR", ), 6 },
        //{ WEAPONDEF_FIELD("proneMoveU", ), 6 },
        //{ WEAPONDEF_FIELD("proneRotP", ), 6 },
        //{ WEAPONDEF_FIELD("proneRotY", ), 6 },
        //{ WEAPONDEF_FIELD("proneRotR", ), 6 },
        //{ WEAPONDEF_FIELD("posMoveRate", ), 6 },
        //{ WEAPONDEF_FIELD("posProneMoveRate", ), 6 },
        //{ WEAPONDEF_FIELD("standMoveMinSpeed", ), 6 },
        //{ WEAPONDEF_FIELD("duckedMoveMinSpeed", ), 6 },
        //{ WEAPONDEF_FIELD("proneMoveMinSpeed", ), 6 },
        //{ WEAPONDEF_FIELD("posRotRate", ), 6 },
        //{ WEAPONDEF_FIELD("posProneRotRate", ), 6 },
        //{ WEAPONDEF_FIELD("standRotMinSpeed", ), 6 },
        //{ WEAPONDEF_FIELD("duckedRotMinSpeed", ), 6 },
        //{ WEAPONDEF_FIELD("proneRotMinSpeed", ), 6 },
        //{ WEAPONDEF_FIELD("worldModel", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel2", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel3", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel4", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel5", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel6", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel7", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel8", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel9", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel10", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel11", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel12", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel13", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel14", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel15", ), 9 },
        //{ WEAPONDEF_FIELD("worldModel16", ), 9 },
        //{ WEAPONDEF_FIELD("worldClipModel", ), 9 },
        //{ WEAPONDEF_FIELD("rocketModel", ), 9 },
        //{ WEAPONDEF_FIELD("knifeModel", ), 9 },
        //{ WEAPONDEF_FIELD("worldKnifeModel", ), 9 },
        //{ WEAPONDEF_FIELD("hudIcon", ), 0xA },
        //{ WEAPONDEF_FIELD("hudIconRatio", ), 0x1D },
        //{ WEAPONDEF_FIELD("ammoCounterIcon", ), 0xA },
        //{ WEAPONDEF_FIELD("ammoCounterIconRatio", ), 0x1E },
        //{ WEAPONDEF_FIELD("ammoCounterClip", ), 0x1C },
        //{ WEAPONDEF_FIELD("startAmmo", ), 4 },
        //{ WEAPONDEF_FIELD("ammoName", ), 0 },
        //{ WEAPONDEF_FIELD("clipName", ), 0 },
        //{ WEAPONDEF_FIELD("maxAmmo", ), 4 },
        //{ WEAPONDEF_FIELD("clipSize", ), 4 },
        //{ WEAPONDEF_FIELD("shotCount", ), 4 },
        { "displayName", 0x4, 0  },
        { "AIOverlayDescription", 0x8, 0 },
        { "modeName", 0xD4, 0 },
        { "playerAnimType", 0x128, 0x14 },
        { "gunModel", 0xC, 9 },
        { "gunModel2", 0x10, 9 },
        { "gunModel3", 0x14, 9 },
        { "gunModel4", 0x18, 9 },
        { "gunModel5", 0x1C, 9 },
        { "gunModel6", 0x20, 9 },
        { "gunModel7", 0x24, 9 },
        { "gunModel8", 0x28, 9 },
        { "gunModel9", 0x2C, 9 },
        { "gunModel10", 0x30, 9 },
        { "gunModel11", 0x34, 9 },
        { "gunModel12", 0x38, 9 },
        { "gunModel13", 0x3C, 9 },
        { "gunModel14", 0x40, 9 },
        { "gunModel15", 0x44, 9 },
        { "gunModel16", 0x48, 9 },
        { "handModel", 0x4C, 9 },
        { "hideTags", 0xD8, 0x21 },
        { "notetrackSoundMap", 0xE8, 0x22 },
        { "idleAnim", 0x54, 0 },
        { "emptyIdleAnim", 0x58, 0 },
        { "fireAnim", 0x5C, 0 },
        { "holdFireAnim", 0x60, 0 },
        { "lastShotAnim", 0x64, 0 },
        { "detonateAnim", 0xB4, 0 },
        { "rechamberAnim", 0x68, 0 },
        { "meleeAnim", 0x6C, 0 },
        { "meleeChargeAnim", 0x70, 0 },
        { "reloadAnim", 0x74, 0 },
        { "reloadEmptyAnim", 0x78, 0 },
        { "reloadStartAnim", 0x7C, 0 },
        { "reloadEndAnim", 0x80, 0 },
        { "raiseAnim", 0x84, 0 },
        { "dropAnim", 0x8C, 0 },
        { "firstRaiseAnim", 0x88, 0 },
        { "altRaiseAnim", 0x90, 0 },
        { "altDropAnim", 0x94, 0 },
        { "quickRaiseAnim", 0x98, 0 },
        { "quickDropAnim", 0x9C, 0 },
        { "emptyRaiseAnim", 0xA0, 0 },
        { "emptyDropAnim", 0xA4, 0 },
        { "sprintInAnim", 0xA8, 0 },
        { "sprintLoopAnim", 0xAC, 0 },
        { "sprintOutAnim", 0xB0, 0 },
        { "nightVisionWearAnim", 0xB8, 0 },
        { "nightVisionRemoveAnim", 0xBC, 0 },
        { "adsFireAnim", 0xC0, 0 },
        { "adsLastShotAnim", 0xC4, 0 },
        { "adsRechamberAnim", 0xC8, 0 },
        { "adsUpAnim", 0xCC, 0 },
        { "adsDownAnim", 0xD0, 0 },
        { "script", 0x7F4, 0 },
        { "weaponType", 0x12C, 0x0C },
        { "weaponClass", 0x130, 0x0D },
        { "penetrateType", 0x134, 0x0F },
        { "impactType", 0x138, 0x10 },
        { "inventoryType", 0x13C, 0x1A },
        { "fireType", 0x140, 0x1B },
        { "offhandClass", 0x144, 0x13 },
        { "viewFlashEffect", 0x14C, 8 },
        { "worldFlashEffect", 0x150, 8 },
        { "pickupSound", 0x154, 0x0B },
        { "pickupSoundPlayer", 0x158, 0x0B },
        { "ammoPickupSound", 0x15C, 0x0B },
        { "ammoPickupSoundPlayer", 0x160, 0x0B },
        { "projectileSound", 0x164, 0x0B },
        { "pullbackSound", 0x168, 0x0B },
        { "pullbackSoundPlayer", 0x16C, 0x0B },
        { "fireSound", 0x170, 0x0B },
        { "fireSoundPlayer", 0x174, 0x0B },
        { "loopFireSound", 0x178, 0x0B },
        { "loopFireSoundPlayer", 0x17C },
        {"stopFireSound", 0x180, 0x0B },
        {"stopFireSoundPlayer", 0x184, 0x0B },
        {"lastShotSound", 0x188, 0x0B },
        {"lastShotSoundPlayer", 0x18C, 0x0B },
        {"emptyFireSound", 0x190, 0x0B },
        { "emptyFireSoundPlayer", 0x194, 0x0B },
        { "meleeSwipeSound", 0x198, 0x0B },
        { "meleeSwipeSoundPlayer", 0x19C, 0x0B },
        { "meleeHitSound", 0x1A0, 0x0B },
        { "meleeMissSound", 0x1A4, 0x0B },
        { "rechamberSound", 0x1A8, 0x0B },
        { "rechamberSoundPlayer", 0x1AC, 0x0B },
        { "reloadSound", 0x1B0, 0x0B },
        { "reloadSoundPlayer", 0x1B4, 0x0B },
        { "reloadEmptySound", 0x1B8, 0x0B },
        { "reloadEmptySoundPlayer", 0x1BC, 0x0B },
        { "reloadStartSound", 0x1C0, 0x0B },
        { "reloadStartSoundPlayer", 0x1C4, 0x0B },
        { "reloadEndSound", 0x1C8, 0x0B },
        { "reloadEndSoundPlayer", 0x1CC, 0x0B },
        { "detonateSound", 0x1D0, 0x0B },
        { "detonateSoundPlayer", 0x1D4, 0x0B },
        { "nightVisionWearSound", 0x1D8, 0x0B },
        { "nightVisionWearSoundPlayer", 0x1DC, 0x0B },
        { "nightVisionRemoveSound", 0x1E0, 0x0B },
        { "nightVisionRemoveSoundPlayer", 0x1E4, 0x0B },
        { "raiseSound", 0x1F0, 0x0B },
        { "raiseSoundPlayer", 0x1F4, 0x0B },
        { "firstRaiseSound", 0x1F8, 0x0B },
        { "firstRaiseSoundPlayer", 0x1FC, 0x0B },
        { "altSwitchSound", 0x1E8, 0x0B },
        { "altSwitchSoundPlayer", 0x1EC, 0x0B },
        { "putawaySound", 0x200, 0x0B },
        { "putawaySoundPlayer", 0x204, 0x0B },
        { "bounceSound", 0x208, 0x17 },
        { "viewShellEjectEffect", 0x20C, 8 },
        { "worldShellEjectEffect", 0x210, 8 },
        { "viewLastShotEjectEffect", 0x214, 8 },
        { "worldLastShotEjectEffect", 0x218, 8 },
        { "reticleCenter", 0x21C, 0xA },
        { "reticleSide", 0x220, 0xA },
        { "reticleCenterSize", 0x224, 4 },
        { "reticleSideSize", 0x228, 4 },
        { "reticleMinOfs", 0x22C, 4 },
        { "activeReticleType", 0x230, 0x15 },
        { "standMoveF", 0x234, 6 },
        { "standMoveR", 0x238, 6 },
        { "standMoveU", 0x23C, 6 },
        { "standRotP", 0x240, 6 },
        { "standRotY", 0x244, 6 },
        { "standRotR", 0x248, 6 },
        { "duckedOfsF", 0x24C, 6 },
        { "duckedOfsR", 0x250, 6 },
        { "duckedOfsU", 0x254, 6 },
        { "duckedMoveF", 0x258, 6 },
        { "duckedMoveR", 0x25C, 6 },
        { "duckedMoveU", 0x260, 6 },
        { "duckedRotP", 0x264, 6 },
        { "duckedRotY", 0x268, 6 },
        { "duckedRotR", 0x26C, 6 },
        { "proneOfsF", 0x270, 6 },
        { "proneOfsR", 0x274, 6 },
        { "proneOfsU", 0x278, 6 },
        { "proneMoveF", 0x27C, 6 },
        { "proneMoveR", 0x280, 6 },
        { "proneMoveU", 0x284, 6 },
        { "proneRotP", 0x288, 6 },
        { "proneRotY", 0x28C, 6 },
        { "proneRotR", 0x290, 6 },
        { "posMoveRate", 0x294, 6 },
        { "posProneMoveRate", 0x298, 6 },
        { "standMoveMinSpeed", 0x29C, 6 },
        { "duckedMoveMinSpeed", 0x2A0, 6 },
        { "proneMoveMinSpeed", 0x2A4, 6 },
        { "posRotRate", 0x2A8, 6 },
        { "posProneRotRate", 0x2AC, 6 },
        { "standRotMinSpeed", 0x2B0, 6 },
        { "duckedRotMinSpeed", 0x2B4, 6 },
        { "proneRotMinSpeed", 0x2B8, 6 },
        { "worldModel", 0x2BC, 9 },
        { "worldModel2", 0x2C0, 9 },
        { "worldModel3", 0x2C4, 9 },
        { "worldModel4", 0x2C8, 9 },
        { "worldModel5", 0x2CC, 9 },
        { "worldModel6", 0x2D0, 9 },
        { "worldModel7", 0x2D4, 9 },
        { "worldModel8", 0x2D8, 9 },
        { "worldModel9", 0x2DC, 9 },
        { "worldModel10", 0x2E0, 9 },
        { "worldModel11", 0x2E4, 9 },
        { "worldModel12", 0x2E8, 9 },
        { "worldModel13", 0x2EC, 9 },
        { "worldModel14", 0x2F0, 9 },
        { "worldModel15", 0x2F4, 9 },
        { "worldModel16", 0x2F8, 9 },
        { "worldClipModel", 0x2FC, 9 },
        { "rocketModel", 0x300, 9 },
        { "knifeModel", 0x304, 9 },
        { "worldKnifeModel", 0x308, 9 },
        { "hudIcon", 0x30C, 0xA },
        { "hudIconRatio", 0x310, 0x1D },
        { "ammoCounterIcon", 0x314, 0xA },
        { "ammoCounterIconRatio", 0x318, 0x1E },
        { "ammoCounterClip", 0x31C, 0x1C },
        { "startAmmo", 0x320, 4 },
        { "ammoName", 0x324, 0 },
        { "clipName", 0x32C, 0 },
        { "maxAmmo", 0x334, 4 },
        { "clipSize", 0x338, 4 },
        { "shotCount", 0x33C, 4 },
        { "sharedAmmoCapName", 0x340, 0 },
        { "sharedAmmoCap", 0x348, 4 },
        { "damage", 0x34C, 4 },
        { "playerDamage", 0x350, 4 },
        { "meleeDamage", 0x354, 4 },
        { "minDamage", 0x800, 4 },
        { "minPlayerDamage", 0x804, 4 },
        { "maxDamageRange", 0x808, 6 },
        { "minDamageRange", 0x80C, 6 },
        { "destabilizationRateTime", 0x810, 6 },
        { "destabilizationCurvatureMax", 0x814, 6 },
        { "destabilizeDistance", 0x818, 4 },
        { "fireDelay", 0x35C, 7 },
        { "meleeDelay", 0x360, 7 },
        { "meleeChargeDelay", 0x364, 7 },
        { "fireTime", 0x36C, 7 },
        { "rechamberTime", 0x370, 7 },
        { "rechamberBoltTime", 0x374, 7 },
        { "holdFireTime", 0x378, 7 },
        { "detonateTime", 0x37C, 7 },
        { "detonateDelay", 0x368, 7 },
        { "meleeTime", 0x380, 7 },
        { "meleeChargeTime", 0x384, 7 },
        { "reloadTime", 0x388, 7 },
        { "reloadShowRocketTime", 0x38C, 7 },
        { "reloadEmptyTime", 0x390, 7 },
        { "reloadAddTime", 0x394, 7 },
        { "reloadStartTime", 0x398, 7 },
        { "reloadStartAddTime", 0x39C, 7 },
        { "reloadEndTime", 0x3A0, 7 },
        { "dropTime", 0x3A4, 7 },
        { "raiseTime", 0x3A8, 7 },
        { "altDropTime", 0x3AC, 7 },
        { "altRaiseTime", 0x3B0, 7 },
        { "quickDropTime", 0x3B4, 7 },
        { "quickRaiseTime", 0x3B8, 7 },
        { "firstRaiseTime", 0x3BC, 7 },
        { "emptyRaiseTime", 0x3C0, 7 },
        { "emptyDropTime", 0x3C4, 7 },
        { "sprintInTime", 0x3C8, 7 },
        { "sprintLoopTime", 0x3CC, 7 },
        { "sprintOutTime", 0x3D0, 7 },
        { "nightVisionWearTime", 0x3D4, 7 },
        { "nightVisionWearTimeFadeOutEnd", 0x3D8, 7 },
        { "nightVisionWearTimePowerUp", 0x3DC, 7 },
        { "nightVisionRemoveTime", 0x3E0, 7 },
        { "nightVisionRemoveTimePowerDown", 0x3E4, 7 },
        { "nightVisionRemoveTimeFadeInStart", 0x3E8, 7 },
        { "fuseTime", 0x3EC, 7 },
        { "aifuseTime", 0x3F0, 7 },
        { "requireLockonToFire", 0x3F4, 5 },
        { "noAdsWhenMagEmpty", 0x3F8, 5 },
        { "avoidDropCleanup", 0x3FC, 5 },
        { "autoAimRange", 0x400, 6 },
        { "aimAssistRange", 0x404, 6 },
        { "aimAssistRangeAds", 0x408, 6 },
        { "aimPadding", 0x40C, 6 },
        { "enemyCrosshairRange", 0x410, 6 },
        { "crosshairColorChange", 0x414, 5 },
        { "moveSpeedScale", 0x418, 6 },
        { "adsMoveSpeedScale", 0x41C, 6 },
        { "sprintDurationScale", 0x420, 6 },
        { "idleCrouchFactor", 0x49C, 6 },
        { "idleProneFactor", 0x4A0, 6 },
        { "gunMaxPitch", 0x4A4, 6 },
        { "gunMaxYaw", 0x4A8, 6 },
        { "swayMaxAngle", 0x4AC, 6 },
        { "swayLerpSpeed", 0x4B0, 6 },
        { "swayPitchScale", 0x4B4, 6 },
        { "swayYawScale", 0x4B8, 6 },
        { "swayHorizScale", 0x4BC, 6 },
        { "swayVertScale", 0x4C0, 6 },
        { "swayShellShockScale", 0x4C4, 6 },
        { "adsSwayMaxAngle", 0x4C8, 6 },
        { "adsSwayLerpSpeed", 0x4CC, 6 },
        { "adsSwayPitchScale", 0x4D0, 6 },
        { "adsSwayYawScale", 0x4D4, 6 },
        { "adsSwayHorizScale", 0x4D8, 6 },
        { "adsSwayVertScale", 0x4DC, 6 },
        { "rifleBullet", 0x4E0, 5 },
        { "armorPiercing", 0x4E4, 5 },
        { "boltAction", 0x4E8, 5 },
        { "aimDownSight", 0x4EC, 5 },
        { "rechamberWhileAds", 0x4F0, 5 },
        { "adsViewErrorMin", 0x4F4, 6 },
        { "adsViewErrorMax", 0x4F8, 6 },
        { "clipOnly", 0x500, 5 },
        { "cookOffHold", 0x4FC, 5 },
        { "adsFire", 0x504, 5 },
        { "cancelAutoHolsterWhenEmpty", 0x508, 5 },
        { "suppressAmmoReserveDisplay", 0x50C, 5 },
        { "enhanced", 0x510, 5 },
        { "laserSightDuringNightvision", 0x514, 5 },
        { "killIcon", 0x518, 0xA },
        { "killIconRatio", 0x51C, 0x1F },
        { "flipKillIcon", 0x520, 5 },
        { "dpadIcon", 0x524, 0xA },
        { "dpadIconRatio", 0x528, 0x20 },
        { "noPartialReload", 0x52C, 5 },
        { "segmentedReload", 0x530, 5 },
        { "reloadAmmoAdd", 0x534, 4 },
        { "reloadStartAdd", 0x538, 4 },
        { "altWeapon", 0x53C, 0 },
        { "dropAmmoMin", 0x544, 4 },
        { "dropAmmoMax", 0x548, 4 },
        { "blocksProne", 0x54C, 5 },
        { "silenced", 0x550, 5 },
        { "explosionRadius", 0x554, 4 },
        { "explosionRadiusMin", 0x558, 4 },
        { "explosionInnerDamage", 0x55C, 4 },
        { "explosionOuterDamage", 0x560, 4 },
        { "damageConeAngle", 0x564, 6 },
        { "projectileSpeed", 0x568, 4 },
        { "projectileSpeedUp", 0x56C, 4 },
        { "projectileSpeedForward", 0x570, 4 },
        { "projectileActivateDist", 0x574, 4 },
        { "projectileLifetime", 0x578, 6 },
        { "timeToAccelerate", 0x57C, 6 },
        { "projectileCurvature", 0x580, 6 },
        { "projectileModel", 0x584, 9 },
        { "projExplosionType", 0x588, 0x12 },
        { "projExplosionEffect", 0x58C, 8 },
        { "projExplosionEffectForceNormalUp", 0x590, 5 },
        { "projExplosionSound", 0x598, 0xB },
        { "projDudEffect", 0x594, 8 },
        { "projDudSound", 0x59C, 0xB },
        { "projImpactExplode", 0x5A0, 5 },
        { "stickiness", 0x5A4, 0x18 },
        { "hasDetonator", 0x5A8, 5 },
        { "timedDetonation", 0x5AC, 5 },
        { "rotate", 0x5B0, 5 },
        { "holdButtonToThrow", 0x5B4, 5 },
        { "freezeMovementWhenFiring", 0x5B8, 5 },
        { "lowAmmoWarningThreshold", 0x5BC, 6 },
        { "parallelDefaultBounce", 0x5C0, 6 },
        { "parallelBarkBounce", 0x5C4, 6 },
        { "parallelBrickBounce", 0x5C8, 6 },
        { "parallelCarpetBounce", 0x5CC, 6 },
        { "parallelClothBounce", 0x5D0, 6 },
        { "parallelConcreteBounce", 0x5D4, 6 },
        { "parallelDirtBounce", 0x5D8, 6 },
        { "parallelFleshBounce", 0x5DC, 6 },
        { "parallelFoliageBounce", 0x5E0, 6 },
        { "parallelGlassBounce", 0x5E4, 6 },
        { "parallelGrassBounce", 0x5E8, 6 },
        { "parallelGravelBounce", 0x5EC, 6 },
        { "parallelIceBounce", 0x5F0, 6 },
        { "parallelMetalBounce", 0x5F4, 6 },
        { "parallelMudBounce", 0x5F8, 6 },
        { "parallelPaperBounce", 0x5FC, 6 },
        { "parallelPlasterBounce", 0x600, 6 },
        { "parallelRockBounce", 0x604, 6 },
        { "parallelSandBounce", 0x608, 6 },
        { "parallelSnowBounce", 0x60C, 6 },
        { "parallelWaterBounce", 0x610, 6 },
        { "parallelWoodBounce", 0x614, 6 },
        { "parallelAsphaltBounce", 0x618, 6 },
        { "parallelCeramicBounce", 0x61C, 6 },
        { "parallelPlasticBounce", 0x620, 6 },
        { "parallelRubberBounce", 0x624, 6 },
        { "parallelCushionBounce", 0x628, 6 },
        { "parallelFruitBounce", 0x62C, 6 },
        { "parallelPaintedMetalBounce", 0x630, 6 },
        { "perpendicularDefaultBounce", 0x634, 6 },
        { "perpendicularBarkBounce", 0x638, 6 },
        { "perpendicularBrickBounce", 0x63C, 6 },
        { "perpendicularCarpetBounce", 0x640, 6 },
        { "perpendicularClothBounce", 0x644, 6 },
        { "perpendicularConcreteBounce", 0x648, 6 },
        { "perpendicularDirtBounce", 0x64C, 6 },
        { "perpendicularFleshBounce", 0x650, 6 },
        { "perpendicularFoliageBounce", 0x654, 6 },
        { "perpendicularGlassBounce", 0x658, 6 },
        { "perpendicularGrassBounce", 0x65C, 6 },
        { "perpendicularGravelBounce", 0x660, 6 },
        { "perpendicularIceBounce", 0x664, 6 },
        { "perpendicularMetalBounce", 0x668, 6 },
        { "perpendicularMudBounce", 0x66C, 6 },
        { "perpendicularPaperBounce", 0x670, 6 },
        { "perpendicularPlasterBounce", 0x674, 6 },
        { "perpendicularRockBounce", 0x678, 6 },
        { "perpendicularSandBounce", 0x67C, 6 },
        { "perpendicularSnowBounce", 0x680, 6 },
        { "perpendicularWaterBounce", 0x684, 6 },
        { "perpendicularWoodBounce", 0x688, 6 },
        { "perpendicularAsphaltBounce", 0x68C, 6 },
        { "perpendicularCeramicBounce", 0x61C, 6 },
        { "perpendicularPlasticBounce", 0x620, 6 },
        { "perpendicularRubberBounce", 0x624, 6 },
        { "perpendicularCushionBounce", 0x69C, 6 },
        { "perpendicularFruitBounce", 0x6A0, 6 },
        { "perpendicularPaintedMetalBounce", 0x6A4, 6 },
        { "projTrailEffect", 0x6A8, 8 },
        { "projectileRed", 0x6AC, 6 },
        { "projectileGreen", 0x6B0, 6 },
        { "projectileBlue", 0x6B4, 6 },
        { "guidedMissileType", 0x6B8, 0x16 },
        { "maxSteeringAccel", 0x6BC, 6 },
        { "projIgnitionDelay", 0x6C0, 4 },
        { "projIgnitionEffect", 0x6C4, 8 },
        { "projIgnitionSound", 0x6C8, 0x0B },
        { "adsTransInTime", 0x484, 7 },
        { "adsTransOutTime", 0x488, 7 },
        { "adsIdleAmount", 0x48C, 6 },
        { "adsIdleSpeed", 0x494, 6 },
        { "adsZoomFov", 0x424, 6 },
        { "adsZoomInFrac", 0x428, 6 },
        { "adsZoomOutFrac", 0x42C, 6 },
        { "adsOverlayShader", 0x430, 0xA },
        { "adsOverlayShaderLowRes", 0x434, 0xA },
        { "adsOverlayReticle", 0x438, 0xE },
        { "adsOverlayInterface", 0x43C, 0x19 },
        { "adsOverlayWidth", 0x440, 6 },
        { "adsOverlayHeight", 0x444, 6 },
        { "adsBobFactor", 0x448, 6 },
        { "adsViewBobMult", 0x44C, 6 },
        { "adsAimPitch", 0x6CC, 6 },
        { "adsCrosshairInFrac", 0x6D0, 6 },
        { "adsCrosshairOutFrac", 0x6D4, 6 },
        { "adsReloadTransTime", 0x794, 7 },
        { "adsGunKickReducedKickBullets", 0x6D8, 4 },
        { "adsGunKickReducedKickPercent", 0x6DC, 6 },
        { "adsGunKickPitchMin", 0x6E0, 6 },
        { "adsGunKickPitchMax", 0x6E4, 6 },
        { "adsGunKickYawMin", 0x6E8, 6 },
        { "adsGunKickYawMax", 0x6EC, 6 },
        { "adsGunKickAccel", 0x6F0, 6 },
        { "adsGunKickSpeedMax", 0x6F4, 6 },
        { "adsGunKickSpeedDecay", 0x6F8, 6 },
        { "adsGunKickStaticDecay", 0x6FC, 6 },
        { "adsViewKickPitchMin", 0x700, 6 },
        { "adsViewKickPitchMax", 0x704, 6 },
        { "adsViewKickYawMin", 0x708, 6 },
        { "adsViewKickYawMax", 0x70C, 6 },
        { "adsViewKickCenterSpeed", 0x710, 6 },
        { "adsSpread", 0x71C, 6 },
        { "guidedMissileType", 0x6B8, 0x16 },
        { "hipSpreadStandMin", 0x450, 6 },
        { "hipSpreadDuckedMin", 0x454, 6 },
        { "hipSpreadProneMin", 0x458, 6 },
        { "hipSpreadMax", 0x45C, 6 },
        { "hipSpreadDuckedMax", 0x460, 6 },
        { "hipSpreadProneMax", 0x464, 6 },
        { "hipSpreadDecayRate", 0x468, 6 },
        { "hipSpreadFireAdd", 0x46C, 6 },
        { "hipSpreadTurnAdd", 0x470, 6 },
        { "hipSpreadMoveAdd", 0x474, 6 },
        { "hipSpreadDuckedDecay", 0x478, 6 },
        { "hipSpreadProneDecay", 0x47C, 6 },
        { "hipReticleSidePos", 0x480, 6 },
        { "hipIdleAmount", 0x490, 6 },
        { "hipIdleSpeed", 0x498, 6 },
        { "hipGunKickReducedKickBullets", 0x720, 4 },
        { "hipGunKickReducedKickPercent", 0x724, 6 },
        { "hipGunKickPitchMin", 0x728, 6 },
        { "hipGunKickPitchMax", 0x72C, 6 },
        { "hipGunKickYawMin", 0x730, 6 },
        { "hipGunKickYawMax", 0x734, 6 },
        { "hipGunKickAccel", 0x738, 6 },
        { "hipGunKickSpeedMax", 0x73C, 6 },
        { "hipGunKickSpeedDecay", 0x740, 6 },
        { "hipGunKickStaticDecay", 0x744, 6 },
        { "hipViewKickPitchMin", 0x748, 6 },
        { "hipViewKickPitchMax", 0x74C, 6 },
        { "hipViewKickYawMin", 0x750, 6 },
        { "hipViewKickYawMax", 0x754, 6 },
        { "hipViewKickCenterSpeed", 0x758, 6 },
        { "leftArc", 0x798, 6 },
        { "rightArc", 0x79C, 6 },
        { "topArc", 0x7A0, 6 },
        { "bottomArc", 0x7A4, 6 },
        { "accuracy", 0x7A8, 6 },
        { "aiSpread", 0x7AC, 6 },
        { "playerSpread", 0x7B0, 6 },
        { "maxVertTurnSpeed", 0x7BC, 6 },
        { "maxHorTurnSpeed", 0x7C0, 6 },
        { "minVertTurnSpeed", 0x7B4, 6 },
        { "minHorTurnSpeed", 0x7B8, 6 },
        { "pitchConvergenceTime", 0x7C4, 6 },
        { "yawConvergenceTime", 0x7C8, 6 },
        { "suppressionTime", 0x7CC, 6 },
        { "maxRange", 0x7D0, 6 },
        { "animHorRotateInc", 0x7D4, 6 },
        { "playerPositionDist", 0x7D8, 6 },
        { "stance", 0x148, 0x11 },
        { "useHintString", 0x7DC, 0 },
        { "dropHintString", 0x7E0, 0 },
        { "horizViewJitter", 0x7EC, 6 },
        { "vertViewJitter", 0x7F0, 6 },
        { "fightDist", 0x764, 6 },
        { "maxDist", 0x768, 6 },
        { "aiVsAiAccuracyGraph", 0x76C, 0 },
        { "aiVsPlayerAccuracyGraph", 0x770, 0 },
        { "locNone", 0x81C, 6 },
        { "locHelmet", 0x820, 6 },
        { "locHead", 0x824, 6 },
        { "locNeck", 0x828, 6 },
        { "locTorsoUpper", 0x82C, 6 },
        { "locTorsoLower", 0x830, 6 },
        { "locRightArmUpper", 0x834, 6 },
        { "locRightArmLower", 0x83C, 6 },
        { "locRightHand", 0x844, 6 },
        { "locLeftArmUpper", 0x838, 6 },
        { "locLeftArmLower", 0x840, 6 },
        { "locLeftHand", 0x848, 6 },
        { "locRightLegUpper", 0x84C, 6 },
        { "locRightLegLower", 0x854, 6 },
        { "locRightFoot", 0x85C, 6 },
        { "locLeftLegUpper", 0x850, 6 },
        { "locLeftLegLower", 0x858, 6 },
        { "locLeftFoot", 0x860, 6 },
        { "locGun", 0x864, 6 },
        { "fireRumble", 0x868, 0 },
        { "meleeImpactRumble", 0x86C, 0 },
        { "adsDofStart", 0x870, 6 },
        { "adsDofEnd", 0x874, 6 },
    };
} // extern "C"
