#include "db_registry.hpp"

bool g_archiveBuf;

void(CDECL* DB_InitPoolHeaderHandler[ASSET_TYPE_COUNT])(void*, int) =
{
    DB_InitPool_XModelPieces, 
    DB_InitPool_PhysPreset, 
    DB_InitPool_XAnimParts, 
    DB_InitPool_XModel, 
    DB_InitPool_Material, 
    DB_InitPool_MaterialTechniqueSet, 
    DB_InitPool_GfxImage, 
    DB_InitPool_snd_alias_list_t, 
    DB_InitPool_SndCurve, 
    DB_InitPool_LoadedSound, 
    DB_InitSingleton, 
    DB_InitSingleton, 
    DB_InitSingleton, 
    DB_InitSingleton, 
    DB_InitSingleton, 
    DB_InitPool_MapEnts, 
    DB_InitSingleton, 
    DB_InitPool_GfxLightDef, 
    0x0, 
    DB_InitPool_Font_s, 
    DB_InitPool_MenuList, 
    DB_InitPool_menuDef_t, 
    DB_InitPool_LocalizeEntry, 
    DB_InitPool_WeaponDef, 
    0x0, 
    DB_InitPool_FxEffectDef, 
    DB_InitPool_FxImpactTable, 
    0x0, 
    0x0, 
    0x0, 
    0x0, 
    DB_InitPool_RawFile, 
    DB_InitPool_StringTable, 
};


extern "C"
{
    char db_hashCritSect[0x8];
    int g_defaultAssetCount;
    XAssetEntryPoolEntry* g_freeAssetEntryHead;
    unsigned int g_zoneAllocType;
    int g_sync;
    bool g_zoneInited;
    XAssetEntry* g_copyInfo[2048];
    unsigned int g_copyInfoCount;
    char g_debugZoneName[0x40];
    char g_mainThreadBlocked[0x80];


    void(CDECL* DB_DynamicCloneXAssetHandler[ASSET_TYPE_COUNT])(XAssetHeader, XAssetHeader, DBCloneMethod) =
    {
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        DB_DynamicCloneMenu,
        nullptr,
        DB_DynamicCloneWeaponDef,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
    };

    const char* g_defaultAssetName[ASSET_TYPE_COUNT] =
    {
        "",
        "default",
        "void",
        "void",
        "$default",
        "default",
        "white",
        "null",
        "default",
        "null.wav",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "light_dynamic",
        "",
        "fonts/consolefont",
        "ui/default.menu",
        "default_menu",
        "CGAME_UNKNOWN",
        "defaultweapon_mp",
        "",
        "misc/missing_fx",
        "default",
        "",
        "",
        "",
        "",
        "",
        "mp/defaultStringTable.csv",
    };

    void(CDECL* DB_RemoveXAssetHandler[ASSET_TYPE_COUNT])(XAssetHeader Header_) =
    {
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        DB_RemoveTechniqueSet,
        DB_RemoveImage,
        nullptr,
        nullptr,
        DB_RemoveLoadedSound,
        DB_RemoveClipMap,
        DB_RemoveClipMap,
        DB_RemoveComWorld,
        nullptr,
        nullptr,
        nullptr,
        DB_RemoveGfxWorld,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr,
        nullptr
    };

    void(CDECL* DB_FreeXAssetHeaderHandler[ASSET_TYPE_COUNT])(void*, XAssetHeader) =
    {
        DB_FreeXAssetHeader_XModelPieces,
        DB_FreeXAssetHeader_PhysPreset,
        DB_FreeXAssetHeader_XAnimParts,
        DB_FreeXAssetHeader_XModel,
        DB_FreeMaterial,
        DB_FreeXAssetHeader_MaterialTechniqueSet,
        DB_FreeXAssetHeader_GfxImage,
        DB_FreeXAssetHeader_snd_alias_list_t,
        DB_FreeXAssetHeader_SndCurve,
        DB_FreeXAssetHeader_LoadedSound,
        DB_FreeXAssetSingleton,
        DB_FreeXAssetSingleton,
        DB_FreeXAssetSingleton,
        DB_FreeXAssetSingleton,
        DB_FreeXAssetSingleton,
        DB_FreeXAssetHeader_MapEnts,
        DB_FreeXAssetSingleton,
        DB_FreeXAssetHeader_GfxLightDef,
        0x0,
        DB_FreeXAssetHeader_Font_s,
        DB_FreeXAssetHeader_MenuList,
        DB_FreeXAssetHeader_menuDef_t,
        DB_FreeXAssetHeader_LocalizeEntry,
        DB_FreeXAssetHeader_WeaponDef,
        0x0,
        DB_FreeXAssetHeader_FxEffectDef,
        DB_FreeXAssetHeader_FxImpactTable,
        0x0,
        0x0,
        0x0,
        0x0,
        DB_FreeXAssetHeader_RawFile,
        DB_FreeXAssetHeader_StringTable,
    };


    void* (CDECL* DB_AllocXAssetHeaderHandler[ASSET_TYPE_COUNT])(void*) =
    {
        DB_AllocXAsset_XModelPieces,
        DB_AllocXAsset_PhysPreset,
        DB_AllocXAsset_XAnimParts,
        DB_AllocXAsset_XModel,
        DB_AllocMaterial,
        DB_AllocXAsset_MaterialTechniqueSet,
        DB_AllocXAsset_GfxImage,
        DB_AllocXAsset_snd_alias_list_t,
        DB_AllocXAsset_SndCurve,
        DB_AllocXAsset_LoadedSound,
        DB_AllocXAssetSingleton,
        DB_AllocXAssetSingleton,
        DB_AllocXAssetSingleton,
        DB_AllocXAssetSingleton,
        DB_AllocXAssetSingleton,
        DB_AllocXAsset_MapEnts,
        DB_AllocXAssetSingleton,
        DB_AllocXAsset_GfxLightDef,
        0x0,
        DB_AllocXAsset_Font_s,
        DB_AllocXAsset_MenuList,
        DB_AllocXAsset_menuDef_t,
        DB_AllocXAsset_LocalizeEntry,
        DB_AllocXAsset_WeaponDef,
        0x0,
        DB_AllocXAsset_FxEffectDef,
        DB_AllocXAsset_FxImpactTable,
        0x0,
        0x0,
        0x0,
        0x0,
        DB_AllocXAsset_RawFile,
        DB_AllocXAsset_StringTable,
    };
}
