#ifndef __MEM_TRACK_H__
#define __MEM_TRACK_H__

enum EMemTrack
{
  TRACK_DEBUG = 0x0,
  TRACK_HUNK = 0x1,
  TRACK_BINARIES = 0x2,
  TRACK_MISC_SWAP = 0x3,
  TRACK_DELIMITER1 = 0x4,
  TRACK_AI = 0x5,
  TRACK_AI_NODES = 0x6,
  TRACK_SCRIPT = 0x7,
  TRACK_FX = 0x8,
  TRACK_GLASS = 0x9,
  TRACK_NETWORK_ENTITY = 0xA,
  TRACK_MISC = 0xB,
  TRACK_FASTFILE = 0xC,
  TRACK_ANIMATION = 0xD,
  TRACK_WORLD_GLOBALS = 0xE,
  TRACK_SOUND_GLOBALS = 0xF,
  TRACK_CLIENT_ANIMSCRIPT = 0x10,
  TRACK_SOUND = 0x11,
  TRACK_DELIMITER2 = 0x12,
  TRACK_RENDERER_GLOBALS = 0x13,
  TRACK_RENDERER_IMAGES = 0x14,
  TRACK_RENDERER_WORLD = 0x15,
  TRACK_RENDERER_MODELS = 0x16,
  TRACK_RENDERER_MISC = 0x17,
  TRACK_CINEMATICS = 0x18,
  TRACK_DELIMITER3 = 0x19,
  TRACK_COLLISION_MISC = 0x1A,
  TRACK_COLLISION_BRUSH = 0x1B,
  TRACK_COLLISION_MODEL_TRI = 0x1C,
  TRACK_COLLISION_TERRAIN = 0x1D,
  TRACK_PHYSICS = 0x1E,
  TRACK_MAP_ENTS = 0x1F,
  TRACK_TEMP = 0x20,
  TRACK_DELIMITER4 = 0x21,
  TRACK_LOCALIZATION = 0x22,
  TRACK_FLAME = 0x23,
  TRACK_UI = 0x24,
  TRACK_TL = 0x25,
  TRACK_ZMEM = 0x26,
  TRACK_FIREMANAGER = 0x27,
  TRACK_PROFILE = 0x28,
  TRACK_WATERSIM = 0x29,
  TRACK_CLIENT = 0x2A,
  TRACK_RECORDER = 0x2B,
  TRACK_RSTREAM = 0x2C,
  TRACK_RENDERER_STREAMBUFFER = 0x2D,
  TRACK_RENDERER_STREAMBUFFER_EXTRA = 0x2E,
  TRACK_GEOSTREAM = 0x2F,
  TRACK_DDL = 0x30,
  TRACK_ONLINE = 0x31,
  TRACK_EMBLEM = 0x32,
  TRACK_MINSPEC_IMAGES = 0x33,
  TRACK_DELIMITER5 = 0x34,
  TRACK_NONE = 0x35,
  TRACK_COUNT = 0x36,
};


void track_physical_alloc(int size, const char *name, int type, int location);
void track_flush_physical_alloc(const char *name, int type);
void track_PrintInfo();

#endif